eureka:
    client:
        fetch-registry: true
        instance:
            hostname: localhost
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
spring:
    application:
        name: PRODUCT-SERVICE
    data:
        mongodb:
            database: productdb
            host: localhost
            port: 27017
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411
