eureka:
    client:
        fetch-registry: true
        instance:
            hostname: localhost
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8085
spring:
    application:
        name: INVENTORY-SERVICE
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: password
        url: jdbc:mysql://localhost:3306/inventoryDB
        username: root
    jpa:
        hibernate:
            ddl-auto: update
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://localhost:9411
